apiVersion: apps/v1
kind: Deployment
metadata:
  name: midterm-mongo
  labels:
    app: midterm-mongo
spec:
  selector:
    matchLabels:
      app: midterm-mongo
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: midterm-mongo
    spec:
      containers:
        - image: mongo:latest
          imagePullPolicy: Always
          name: midterm-mongo
          ports:
          - containerPort: 27017

