apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: midterm-mongo