apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: midterm-redis