apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: midterm-backend